apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo-server
      name: echo-server
    spec:
      containers:
        - name: echo
          image: mendhak/http-https-echo
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
